title: Cairn
permalink: pretty
theme: just-the-docs
site.url: https://cairnrpg.com
logo: "/img/logo.svg"
color_scheme: dark
encoding: UTF-8
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-jtd-toc-nav # headers in the nav bar
  - jekyll-dice-tray # dice tray widget
  - jekyll-hover-popup # preview popup windows for internal links
  - jekyll-image-links # hyperlinked maps
  - rpg-callouts # additional callout formatting options
include:
  - js

callouts:
  note:
    title: Note
    color: puke

# Aux links for the upper right navigation
aux_links:
  "Return to Just The Games":
    - "https://games.puzzledungeon.com/"

# External navigation links
nav_external_links:
  - title: "🐉 Return to Just The Games (OSE)"
    url: https://games.puzzledungeon.com

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 3
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: "k"


# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Cairn RPG was written by Yochai Gal. The Cairn RPG text is licensed under <a href=\"https://creativecommons.org/licenses/by-sa/4.0\">CC-BY-SA 4.0.</a> This site is just a fork of the actual <a href=\"https://cairnrpg.com\">Cairn SRD</a>."
# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# If you want to ignore the monsters folder during builds
#exclude: /resources/monsters

